### ISSUE TITLE
ivy-xref won't open the completion buffer as expected (spacemacs)

### ISSUE THREAD

**Issue by shwsun** [alexmurray/ivy-xref#12]
I am using spacemacs with ivy layer but I noticed that doing `C-M-i` won't bring up the completion buffer as expected. Can someone give some pointer about why it happened? Replacing ivy with helm works as expected so it should be something in the ivy layer. Thx

![screenshot from 2018-05-30 10-46-43](https://user-images.githubusercontent.com/15823053/40859989-a9bb7d76-65b1-11e8-9872-ef4b10869f23.png)

**Comment by alexmurray** [comment]
I am not sure this has anything to do with `ivy-xref` - this is for looking up `xref` cross references - not for completion. Can you please provide more details or perhaps file a bug in the spacemacs repo?

**Comment by shwsun** [comment]
@alexmurray you are absolutely right, it was a mistake. I was referring to the `ivy` display configuration which is explained [here](https://github.com/abo-abo/swiper/wiki/ivy-display-function). Please close this issue and thank you for your kindly reply!
