### ISSUE TITLE
ivy-call: Selecting deleted buffer

### ISSUE THREAD

**Issue by showgood** [alexmurray/ivy-xref#17]
When `xref-find-references` to find references for python code with lsp-python,
upon selecting a result for reference, emacs raised this error: `selecting deleted buffer`.

emacs version: 26.1
OS: macOS Mojave
latest ivy-xref

**Comment by whame** [comment]
It looks like the `(quit-window)` invalidates the reference for `buffer` in

https://github.com/alexmurray/ivy-xref/blob/3d4c35fe2b243d948d8fe02a1f0d76a249d63de9/ivy-xref.el#L87-L93

I discovered that `(quit-window t)` (i.e. with `&optional kill`) doesn't somehow do that... Check my pull request.
