### ISSUE TITLE
preview current candidate?

### ISSUE THREAD

**Issue by mohkale** [alexmurray/ivy-xref#23]
I know we can't have automatic preview of the candidates (because then we'd have to find and open those files), but it'd be nice if we had a command like `ivy-call-and-recenter` (which is used with `counsel-rg`) that when called, navigates to the file referenced by the current candidate and shows it to us.

**Comment by JJPandari** [comment]
> because then we'd have to find and open those files

And in a lot of occasions the candidates are in the same buffer/file, it would be nice to auto-jump to the buffer position while remain the current behavior (= do nothing) if it's not in current buffer.

**Comment by luluman** [comment]
According to the [document of ivy](https://oremacs.com/swiper/), we can have this. 
Please check "5.2.3 Key bindings for multiple selections and actions, keep minibuffer open"

> For repeatedly applying multiple actions or acting on multiple candidates, Ivy does not close the minibuffer between commands. It keeps the minibuffer open for applying subsequent actions.
>
> Adding an extra meta key to the normal key chord invokes the special version of the regular commands that enables applying multiple actions.
>
> C-M-m (ivy-call)
> Is the non-exiting version of C-m (ivy-done).
> 
> Instead of closing the minibuffer, C-M-m allows selecting another candidate or another action. For example, C-M-m on functions list invokes describe-function. When combined with C-n, function descriptions can be invoked quickly in succession.
> 
> C-M-o (ivy-dispatching-call)
> Is the non-exiting version of M-o (ivy-dispatching-done).
> 
> For example, during the counsel-rhythmbox completion, press C-M-o e to en-queue the selected candidate, followed by C-n C-m to play the next candidate - the current action reverts to the default one after C-M-o.
> 
> C-M-n (ivy-next-line-and-call)
> Combines C-n and C-M-m. Moves to next line and applies an action.
> 
> Comes in handy when opening multiple files from counsel-find-file, counsel-git-grep, counsel-ag, counsel-rg, or counsel-locate lists. Just hold C-M-n for rapid-fire default action on each successive element of the list.
> 
> C-M-p (ivy-previous-line-and-call)
> Combines C-p and C-M-m.
> 
> Similar to the above except it moves through the list in the other direction.

If you cancel the action (using c-g), then nothing happens.

**Comment by JJPandari** [comment]
@luluman Oh yes, `C-M-m (ivy-call)` simply works currently! (Of course, it's just `ivy-done` + non-exit) We should close this issue.

**Comment by mohkale** [comment]
Yeah. I suppose you're right.

**Comment by mohkale** [comment]
Wait, no, sorry, I'd still like the option to recenter the display buffer on repeat calls to `ivy-call` in this case:

If the candidate I've found is at the end of a function and appears at the top of the screen, I'd like to be able to recenter the buffer so that I can see some of the body of the function.

**Comment by JJPandari** [comment]
the call action uses `xref--show-pos-in-buf`:

```
xref--show-pos-in-buf is a compiled Lisp function in ‘xref.el’.

(xref--show-pos-in-buf POS BUF)

Goto and display position POS of buffer BUF in a window.
Honor ‘xref--original-window-intent’, run ‘xref-after-jump-hook’
and finally return the window.
```

which has a hook:

```
xref-after-jump-hook is a variable defined in ‘xref.el’.
Its value is (recenter xref-pulse-momentarily)

  This variable may be risky if used as a file-local variable.

Documentation:
Functions called after jumping to an xref.
```

As you can see `recenter` is in the hook so the buffer recenters cursor after the call action. You should be able to position the cursor however you want by changing `recenter` in the hook to some other buffer operation.

**Comment by mohkale** [comment]
Thnx for the update :smile:.

You're completely right. I've managed to get a workflow I really like because of it.

```elisp

```

Now by

**Comment by mohkale** [comment]
Thnx for the update :smile:.

You're completely right. I've managed to get a workflow I really like because of it.

```elisp
(remove-hook 'xref-after-jump-hook 'recenter)

(defun ivy-xref-call-or-done ()
  (interactive)
  (let (orig-point orig-buffer
                   new-point new-buffer)
    (with-ivy-window
      (setq orig-point  (point)
            orig-buffer (current-buffer)))

    (ivy-call)

    (with-ivy-window
      (setq new-point  (point)
            new-buffer (current-buffer)))

    (when (and (eq new-point  orig-point)
               (eq new-buffer orig-buffer))
      (ivy-done))))

(defvar ivy-xref-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map ivy-minibuffer-map)
    map)
  "map for use with ivy-xref.")

(general-def ivy-xref-map
  "C-l" #'ivy-xref-call-or-done
  "M-l" #'ivy-call-and-recenter)

(advice-add 'ivy-xref-show-xrefs :around
            (defun ivy-xref-use-xref-map (func &rest args)
              (let ((ivy-minibuffer-map ivy-xref-map))
                (apply func args))))
```

Now by running `C-l` ivy lets me preview the candidate at point (using `ivy-call`).
If that candidate is the same as before it exits with it. I've also bound `M-l` to
`ivy-call-and-recenter` (same binding I had on swiper) and it works perfectly fine
with ivy-xref. This solution also has the added benefit of keeping the `recenter`
position I set using `ivy-call-and-recenter` instead of recentering as soon as I
jump to a candidate.

Only issue is, I don't like having to advise `ivy-xref-show-xrefs` to get it to use my
own map. Do you know of a way to update the parameters of an ivy-read invocation?

Anyways, for now this issue is complete so I'm closing it. Thank you again.
