### ISSUE TITLE
"Selecting deleted buffer" after #27

### ISSUE THREAD

**Issue by danp** [alexmurray/ivy-xref#28]
Since updating to a version of ivy-xref including #27 I'm now getting "Selected deleted buffer" when using xref-find-references.

Changing `(quit-window t)` back to `(quit-window)` seems to fix it.

I'm using emacs 27.2 installed via homebrew and d12frosted/emacs-plus/emacs-plus@27.

**Comment by danp** [comment]
My relevant `use-package` call:

```
(use-package ivy-xref
  :init
  (setq xref-show-definitions-function #'ivy-xref-show-defs)
  (setq xref-show-xrefs-function #'ivy-xref-show-xrefs))
```

**Comment by alexmurray** [comment]
Thanks, apologies for breaking things - I reverted this change via https://github.com/alexmurray/ivy-xref/commit/45df80767104dd8f4fe957156c82f1d8b77d64d5  just now so this should be available within 24h via melpa.

**Comment by danp** [comment]
No worries! Thanks for the fix, and for ivy-xref. If there's anything I can do to help test some other related change let me know.
