### ISSUE TITLE
Using predefined font face for candidates

### ISSUE THREAD

**Issue by amosbird** [alexmurray/ivy-xref#3]
Hi, currently `ivy-xref` shows all candidates using their original faces which might be hard to read.

![](https://la.wentropy.com/z_Ya.png)

Does it make sense to provide a way that renders all candidates cleanly? Thanks. Also it might be better to have the file:line parts rendered differently :)

**Comment by alexmurray** [comment]
Sure - do you happen to know of another ivy source which use different faces explicitly like this?

**Comment by amosbird** [comment]
> which use different faces explicitly like this
you mean like the screencast I posted? That's from cquery.

I did some research before but cannot find a way to tweak the faces of ivy outputs.
