### ISSUE TITLE
Option to turn off sorting

### ISSUE THREAD

**Issue by MaskRay** [alexmurray/ivy-xref#4]
ivy-xref can be used for language server protocol [`workspace/symbol`] and here is an example in [cquery](https://github.com/cquery-project/cquery/wiki/Emacs#documentworkspace-symbol-search)

The results are sorted on the server side and thus client-side sorting should be disabled.

```elisp
ivy-xref.el:54
-    collection)))
+   (nreverse collection)))
```

I searched for `set name` but the best fit is listed at the bottom
![](https://ptpb.pw/6N6A.jpg)

https://github.com/syl20bnr/spacemacs/pull/10211 adds ivy-xref to the +tools/lsp layer. It will be much appreciated if you could give some advice or push forward that PR (((

**Comment by alexmurray** [comment]
Thanks - I think it makes sense to always use nreverse since at the moment the result list is always in the opposite order to the original xrefs list.

Added in 4d2c437

**Comment by MaskRay** [comment]
Thanks. Another question is if `:sort t` in `(ivy-read ...)` will sort the results? It seems not in my workspace/symbol use case.
